service: serverless-http-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: sa-east-1
  environment: ${file(environment.yml)}

functions:
  - ${file(src/endpoints/hello.yml)}
