service: serverless-http-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: sa-east-1
  environment: ${file(environment.${opt:stage, 'dev'}.yml)}
  memorySize: 124
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - SQS:*
          Resource:
            - "arn:aws:sqs:sa-east-1:737295027616:testQueue"

functions:
  - ${file(src/endpoints/hello.yml)}
  - ${file(src/endpoints/sqs.yml)}
  - ${file(src/triggers/sqs.yml)}
